data:
  image_width: 64
  image_height: 64

model:
  n_levels: 2  # 4
  n_depth: 8  # 32
  hidden_channel_size: 256

training:
  batch_size: 1
  epochs: 10000
  steps_per_epoch: 1000
  lr: 0.0001
  lr_patience: 5
  lr_decay: 0.1
